refine code

diff --git a/transproxy6 b/transproxy6
--- a/transproxy6
+++ b/transproxy6
@@ -8,7 +8,7 @@
 # See /LICENSE for more information.
 #
 
-# set aliases for code compatibility
+# code compatibility
 alias ip="ip -6"
 alias iptables=ip6tables
 alias iptables-save=ip6tables-save
@@ -16,8 +16,12 @@ alias iptables-restore=ip6tables-restore
 
 TRANSPROXY_VERSION=0.2.1
 
-CODE_SYSTEM_NOT_REQUIRED=1
-CODE_WRONG_OPTION=2
+SRC_DIRECT=transproxy6_src_direct
+SRC_PROXY=transproxy6_src_proxy
+SRC_NORMAL=transproxy6_src_normal
+DST_DIRECT=transproxy6_dst_direct
+DST_PROXY=transproxy6_dst_proxy
+DST_SPECIAL=transproxy6_dst_special
 
 _print_usage() {
   # TODO
@@ -115,13 +119,13 @@ error() {
 }
 
 generate_ipset_rules() {
-  _splice_content $SRC_DIRECT_FILES | _remove_empty | _remove_comment | _add_prefix 'add transproxy6_src_direct '
-  _splice_content $SRC_PROXY_FILES | _remove_empty | _remove_comment | _add_prefix 'add transproxy6_src_proxy '
-  _splice_content $SRC_NORMAL_FILES | _remove_empty | _remove_comment | _add_prefix 'add transproxy6_src_normal '
-  _splice_content $DST_DIRECT_FILES | _remove_empty | _remove_comment | _add_prefix 'add transproxy6_dst_direct '
-  _splice_content $DST_PROXY_FILES | _remove_empty | _remove_comment | _add_prefix 'add transproxy6_dst_proxy '
-  _get_reserved_ip | _remove_empty | _remove_comment | _add_prefix 'add transproxy6_dst_special '
-  _get_special_ip | _remove_empty | _remove_comment | _add_prefix 'add transproxy6_dst_special '
+  _splice_content $SRC_DIRECT_FILES | _remove_empty | _remove_comment | _add_prefix "add $SRC_DIRECT "
+  _splice_content $SRC_PROXY_FILES | _remove_empty | _remove_comment | _add_prefix "add $SRC_PROXY "
+  _splice_content $SRC_NORMAL_FILES | _remove_empty | _remove_comment | _add_prefix "add $SRC_NORMAL "
+  _splice_content $DST_DIRECT_FILES | _remove_empty | _remove_comment | _add_prefix "add $DST_DIRECT "
+  _splice_content $DST_PROXY_FILES | _remove_empty | _remove_comment | _add_prefix "add $DST_PROXY "
+  _get_reserved_ip | _remove_empty | _remove_comment | _add_prefix "add $DST_SPECIAL "
+  _get_special_ip | _remove_empty | _remove_comment | _add_prefix "add $DST_SPECIAL "
 }
 
 create_transproxy_chain() {
@@ -134,18 +138,18 @@ create_transproxy_chain() {
 	:TRANSPROXY_DST_FORWARD - [0:0]
 
 	# PREPARE
-	-A TRANSPROXY_SRC_PREPARE -m set --match-set transproxy_dst_special dst -j RETURN
+	-A TRANSPROXY_SRC_PREPARE -m set --match-set $DST_SPECIAL dst -j RETURN
 	-A TRANSPROXY_SRC_PREPARE $IPT_EXTRAS -j TRANSPROXY_SRC_AC
 
 	# SRC
-	-A TRANSPROXY_SRC_AC -m set --match-set transproxy_src_direct src -j RETURN
-	-A TRANSPROXY_SRC_AC -m set --match-set transproxy_src_proxy src -j TRANSPROXY_DST_FORWARD
-	-A TRANSPROXY_SRC_AC -m set --match-set transproxy_src_normal src -j TRANSPROXY_DST_AC
+	-A TRANSPROXY_SRC_AC -m set --match-set $SRC_DIRECT src -j RETURN
+	-A TRANSPROXY_SRC_AC -m set --match-set $SRC_PROXY src -j TRANSPROXY_DST_FORWARD
+	-A TRANSPROXY_SRC_AC -m set --match-set $SRC_NORMAL src -j TRANSPROXY_DST_AC
 	-A TRANSPROXY_SRC_AC -j $SRC_DEFAULT
 
 	# DST
-	-A TRANSPROXY_DST_AC -m set --match-set transproxy_dst_direct dst -j RETURN
-	-A TRANSPROXY_DST_AC -m set --match-set transproxy_dst_proxy dst -j TRANSPROXY_DST_FORWARD
+	-A TRANSPROXY_DST_AC -m set --match-set $DST_DIRECT dst -j RETURN
+	-A TRANSPROXY_DST_AC -m set --match-set $DST_PROXY dst -j TRANSPROXY_DST_FORWARD
 	-A TRANSPROXY_DST_AC -j $DST_DEFAULT
 
 	# TPROXY
@@ -168,11 +172,11 @@ apply_transproxy_rules() {
 
 apply_self_proxy_rules() {
   iptables -t mangle -N TRANSPROXY_DST_PREPARE
-  iptables -t mangle -A TRANSPROXY_DST_PREPARE -m set --match-set transproxy_dst_special dst -j RETURN
+  iptables -t mangle -A TRANSPROXY_DST_PREPARE -m set --match-set $DST_SPECIAL dst -j RETURN
 
   # negate matching in non-[DIRECT|PROXY] mode
-  [ "$DST_DEFAULT" = "RETURN" ] || iptables -t mangle -A TRANSPROXY_DST_PREPARE -m set --match-set transproxy_dst_direct dst -j RETURN
-  [ "$DST_DEFAULT" = "TRANSPROXY_DST_FORWARD" ] || iptables -t mangle -A TRANSPROXY_DST_PREPARE $IPT_EXTRAS -m set --match-set transproxy_dst_proxy dst -j MARK --set-mark 1
+  [ "$DST_DEFAULT" = "RETURN" ] || iptables -t mangle -A TRANSPROXY_DST_PREPARE -m set --match-set $DST_DIRECT dst -j RETURN
+  [ "$DST_DEFAULT" = "TRANSPROXY_DST_FORWARD" ] || iptables -t mangle -A TRANSPROXY_DST_PREPARE $IPT_EXTRAS -m set --match-set $DST_PROXY dst -j MARK --set-mark 1
 
   # avoid traffic loopback issues, reference: https://github.com/v2ray/v2ray-core/issues/2621
   [ -z "$MATCH_MARK" ] || iptables -t mangle -A TRANSPROXY_DST_PREPARE -m mark --mark $MATCH_MARK -j RETURN
@@ -188,10 +192,10 @@ apply_self_proxy_rules() {
 
 prepare_environment() {
   # check environment
-  modinfo xt_TPROXY &>/dev/null || { error "xt_TPROXY kernel module is not supported."; exit $CODE_SYSTEM_NOT_REQUIRED; }
-  command -v ip >/dev/null || { error "ip command not found."; exit $CODE_SYSTEM_NOT_REQUIRED; }
-  command -v ipset >/dev/null || { error "ipset command not found."; exit $CODE_SYSTEM_NOT_REQUIRED; }
-  command -v ip6tables >/dev/null || { error "ip6tables command not found."; exit $CODE_SYSTEM_NOT_REQUIRED; }
+  modinfo xt_TPROXY &>/dev/null || { error "xt_TPROXY kernel module is not supported."; exit 1; }
+  command -v ip >/dev/null || { error "ip command not found."; exit 1; }
+  command -v ipset >/dev/null || { error "ipset command not found."; exit 1; }
+  command -v ip6tables >/dev/null || { error "ip6tables command not found."; exit 1; }
 
   # fix environment, reference: https://nobb.site/2022/02/18/0x72/
   _apply_sysctl net.bridge.bridge-nf-call-ip6tables 0
@@ -217,12 +221,12 @@ flush_rules() {
 
 init_ipset() {
   ipset -exist restore <<- EOF
-	create transproxy6_src_direct hash:ip hashsize 64 family inet
-	create transproxy6_src_proxy hash:ip hashsize 64 family inet
-	create transproxy6_src_normal hash:ip hashsize 64 family inet
-	create transproxy6_dst_direct hash:net hashsize 64 family inet
-	create transproxy6_dst_proxy hash:net hashsize 64 family inet
-	create transproxy6_dst_special hash:net hashsize 64 family inet
+	create $SRC_DIRECT hash:ip hashsize 64 family inet6
+	create $SRC_PROXY hash:ip hashsize 64 family inet6
+	create $SRC_NORMAL hash:ip hashsize 64 family inet6
+	create $DST_DIRECT hash:net hashsize 64 family inet6
+	create $DST_PROXY hash:net hashsize 64 family inet6
+	create $DST_SPECIAL hash:net hashsize 64 family inet6
 	$(generate_ipset_rules)
 	EOF
 }
@@ -284,7 +288,7 @@ parse_args() {
           direct|DIRECT) SRC_DEFAULT=RETURN;;
           proxy|PROXY) SRC_DEFAULT=TRANSPROXY_DST_FORWARD;;
           normal|NORMAL) SRC_DEFAULT=TRANSPROXY_DST_AC;;
-          *) error "wrong option: $1 $2"; exit $CODE_WRONG_OPTION;;
+          *) error "wrong option: $1 $2"; exit 2;;
         esac
         shift 2
         ;;
@@ -292,7 +296,7 @@ parse_args() {
         case "$2" in
           direct|DIRECT) DST_DEFAULT=RETURN;;
           proxy|PROXY) DST_DEFAULT=TRANSPROXY_DST_FORWARD;;
-          *) error "wrong option: $1 $2"; exit $CODE_WRONG_OPTION;;
+          *) error "wrong option: $1 $2"; exit 2;;
         esac
         shift 2
         ;;
@@ -323,7 +327,7 @@ parse_args() {
         ;;
       *)
         error "unknown option: $1"
-        exit $CODE_WRONG_OPTION
+        exit 2
         ;;
     esac
   done
