add ipv6 version

diff --git a/transproxy6 b/transproxy6
--- a/transproxy6
+++ b/transproxy6
@@ -17,7 +17,7 @@ _print_usage() {
   # TODO
   cat << EOF
 transproxy $TRANSPROXY_VERSION
-A bridge of linux and ipv4 transparent proxy.
+A bridge of linux and ipv6 transparent proxy.
 
 USAGE:
     ${0##*/} [OPTIONS]
@@ -55,32 +55,26 @@ _apply_sysctl() {
 }
 
 _get_reserved_ip() {
+  # TODO: review needed
   cat <<- EOF
-	0.0.0.0/8
-	10.0.0.0/8
-	100.64.0.0/10
-	127.0.0.0/8
-	169.254.0.0/16
-	172.16.0.0/12
-	192.0.0.0/24
-	192.0.2.0/24
-	192.31.196.0/24
-	192.52.193.0/24
-	192.88.99.0/24
-	192.168.0.0/16
-	192.175.48.0/24
-	198.18.0.0/15
-	198.51.100.0/24
-	203.0.113.0/24
-	224.0.0.0/4
-	240.0.0.0/4
-	255.255.255.255
+	::/127
+	::ffff:0:0/96
+	::ffff:0:0:0/96
+	64:ff9b::/96
+	100::/64
+	2001::/32
+	2001:20::/28
+	2001:db8::/32
+	2002::/16
+	fc00::/7
+	fe80::/10
+	ff00::/8
 	EOF
 }
 
 _get_special_ip() {
-  echo $SERVERS | tr ',' '\n' | grep -Eo "\b([0-9]{1,3}\.){3}[0-9]{1,3}\b"
-  ip route get 8.8.8.8 | sed 's/^.*src \([^ ]*\).*$/\1/;q'
+  echo $SERVERS | tr ',' '\n' | grep -Ev "\b([0-9]{1,3}\.){3}[0-9]{1,3}\b"
+  ip route get 2001:4860:4860::8888 | sed 's/^.*src \([^ ]*\).*$/\1/;q'
 }
 
 _get_time() {
@@ -115,13 +109,13 @@ error() {
 }
 
 generate_ipset_rules() {
-  _splice_content $SRC_DIRECT_FILES | _remove_empty | _remove_comment | _add_prefix 'add transproxy_src_direct '
-  _splice_content $SRC_PROXY_FILES | _remove_empty | _remove_comment | _add_prefix 'add transproxy_src_proxy '
-  _splice_content $SRC_NORMAL_FILES | _remove_empty | _remove_comment | _add_prefix 'add transproxy_src_normal '
-  _splice_content $DST_DIRECT_FILES | _remove_empty | _remove_comment | _add_prefix 'add transproxy_dst_direct '
-  _splice_content $DST_PROXY_FILES | _remove_empty | _remove_comment | _add_prefix 'add transproxy_dst_proxy '
-  _get_reserved_ip | _remove_empty | _remove_comment | _add_prefix 'add transproxy_dst_special '
-  _get_special_ip | _remove_empty | _remove_comment | _add_prefix 'add transproxy_dst_special '
+  _splice_content $SRC_DIRECT_FILES | _remove_empty | _remove_comment | _add_prefix 'add transproxy6_src_direct '
+  _splice_content $SRC_PROXY_FILES | _remove_empty | _remove_comment | _add_prefix 'add transproxy6_src_proxy '
+  _splice_content $SRC_NORMAL_FILES | _remove_empty | _remove_comment | _add_prefix 'add transproxy6_src_normal '
+  _splice_content $DST_DIRECT_FILES | _remove_empty | _remove_comment | _add_prefix 'add transproxy6_dst_direct '
+  _splice_content $DST_PROXY_FILES | _remove_empty | _remove_comment | _add_prefix 'add transproxy6_dst_proxy '
+  _get_reserved_ip | _remove_empty | _remove_comment | _add_prefix 'add transproxy6_dst_special '
+  _get_special_ip | _remove_empty | _remove_comment | _add_prefix 'add transproxy6_dst_special '
 }
 
 create_transproxy_chain() {
@@ -149,8 +143,8 @@ create_transproxy_chain() {
 	-A TRANSPROXY_DST_AC -j $DST_DEFAULT
 
 	# TPROXY
-	-A TRANSPROXY_DST_FORWARD -p tcp -j TPROXY --on-ip 127.0.0.1 --on-port $TCP_PORT --tproxy-mark 1
-	-A TRANSPROXY_DST_FORWARD -p udp -j TPROXY --on-ip 127.0.0.1 --on-port $UDP_PORT --tproxy-mark 1
+	-A TRANSPROXY_DST_FORWARD -p tcp -j TPROXY --on-ip ::1 --on-port $TCP_PORT --tproxy-mark 1
+	-A TRANSPROXY_DST_FORWARD -p udp -j TPROXY --on-ip ::1 --on-port $UDP_PORT --tproxy-mark 1
 
 	COMMIT
 	EOF
@@ -187,16 +181,21 @@ apply_self_proxy_rules() {
 }
 
 prepare_environment() {
+  # set aliases for code compatibility
+  alias ip="ip -6"
+  alias iptables=ip6tables
+  alias iptables-save=ip6tables-save
+  alias iptables-restore=ip6tables-restore
+
   # check environment
   modinfo xt_TPROXY &>/dev/null || { error "xt_TPROXY kernel module is not supported."; exit $CODE_SYSTEM_NOT_REQUIRED; }
   command -v ip >/dev/null || { error "ip command not found."; exit $CODE_SYSTEM_NOT_REQUIRED; }
   command -v ipset >/dev/null || { error "ipset command not found."; exit $CODE_SYSTEM_NOT_REQUIRED; }
-  command -v iptables >/dev/null || { error "iptables command not found."; exit $CODE_SYSTEM_NOT_REQUIRED; }
+  command -v ip6tables >/dev/null || { error "ip6tables command not found."; exit $CODE_SYSTEM_NOT_REQUIRED; }
 
-  # fix environment
-  # reference: https://nobb.site/2022/02/18/0x72/
-  _apply_sysctl net.bridge.bridge-nf-call-iptables 0
-  warn "TPROXY requires net.bridge.bridge-nf-call-iptables=0, applied."
+  # fix environment, reference: https://nobb.site/2022/02/18/0x72/
+  _apply_sysctl net.bridge.bridge-nf-call-ip6tables 0
+  warn "TPROXY requires net.bridge.bridge-nf-call-ip6tables=0, applied."
 }
 
 flush_rules() {
@@ -208,7 +207,7 @@ flush_rules() {
   ip route flush table 100 2>/dev/null
   info "strategy route removed."
 
-  for name in $(ipset -n list | grep "transproxy_"); do
+  for name in $(ipset -n list | grep "transproxy6_"); do
     ipset flush $name 2>/dev/null
     ipset destroy $name 2>/dev/null
     debug "ipset $name destroyed."
@@ -218,12 +217,12 @@ flush_rules() {
 
 init_ipset() {
   ipset -exist restore <<- EOF
-	create transproxy_src_direct hash:ip hashsize 64 family inet
-	create transproxy_src_proxy hash:ip hashsize 64 family inet
-	create transproxy_src_normal hash:ip hashsize 64 family inet
-	create transproxy_dst_direct hash:net hashsize 64 family inet
-	create transproxy_dst_proxy hash:net hashsize 64 family inet
-	create transproxy_dst_special hash:net hashsize 64 family inet
+	create transproxy6_src_direct hash:ip hashsize 64 family inet
+	create transproxy6_src_proxy hash:ip hashsize 64 family inet
+	create transproxy6_src_normal hash:ip hashsize 64 family inet
+	create transproxy6_dst_direct hash:net hashsize 64 family inet
+	create transproxy6_dst_proxy hash:net hashsize 64 family inet
+	create transproxy6_dst_special hash:net hashsize 64 family inet
 	$(generate_ipset_rules)
 	EOF
 }
