refine code

diff --git a/transproxy b/transproxy
--- a/transproxy
+++ b/transproxy
@@ -8,10 +8,7 @@
 # See /LICENSE for more information.
 #
 
-# TODO:
-#   1. Check OUTPUT chain should use -A ... or -I, which better?
-
-TRANSPROXY_VERSION=0.1.7
+TRANSPROXY_VERSION=0.1.9
 
 _print_usage() {
   # TODO
@@ -20,7 +17,7 @@ transproxy $TRANSPROXY_VERSION
 A bridge of linux and transparent proxy.
 
 USAGE:
-    $0 [OPTIONS]
+    ${0##*/} [OPTIONS]
 
 OPTIONS:
     -f, --flush    Flush iptables, ipset then exit
@@ -51,7 +48,7 @@ _splice_content() {
 }
 
 _apply_sysctl() {
-  [ $(sysctl -n "$1") != "$2" ] && sysctl -w "$1"="$2"
+  [ $(sysctl -n "$1") = "$2" ] || sysctl -w "$1"="$2"
 }
 
 _get_reserved_ipv4() {
@@ -98,10 +95,12 @@ _get_reserved_ipv6() {
 
 _get_special_ipv4() {
   echo $SERVERS | tr ',' '\n' | grep -Eo "\b([0-9]{1,3}\.){3}[0-9]{1,3}\b"
+  ip route get 8.8.8.8 | sed 's/^.*src \([^ ]*\).*$/\1/;q'
 }
 
 _get_special_ipv6() {
   echo $SERVERS | tr ',' '\n' | grep -Ev "\b([0-9]{1,3}\.){3}[0-9]{1,3}\b"
+  ip -6 route get 2001:4860:4860::8888 | sed 's/^.*src \([^ ]*\).*$/\1/;q'
 }
 
 _get_time() {
@@ -115,30 +114,25 @@ debug() {
 }
 
 info() {
-  local pure='\e[0m'
   local green='\e[0;32m'
+  local clear='\e[0m'
   local time=$(_get_time)
-  printf "${green}[${time}] [INFO]: ${pure}%s\n" "$*"
+  printf "${green}[${time}] [INFO]: ${clear}%s\n" "$*"
 }
 
 warn() {
-  local pure='\e[0m'
   local yellow='\e[1;33m'
+  local clear='\e[0m'
   local time=$(_get_time)
-  printf "${yellow}[${time}] [WARN]: ${pure}%s\n" "$*" >&2
+  printf "${yellow}[${time}] [WARN]: ${clear}%s\n" "$*" >&2
 }
 
 error() {
-  local pure='\e[0m'
   local red='\e[0;31m'
+  local clear='\e[0m'
   local time=$(_get_time)
-  printf "${red}[${time}] [ERROR]: ${pure}%s\n" "$*" >&2
+  printf "${red}[${time}] [ERROR]: ${clear}%s\n" "$*" >&2
 }
-
-#log() {
-#  # 1:alert, 2:crit, 3:err, 4:warn, 5:notice, 6:info, 7:debug, 8:emerg
-#  logger -st transproxy[$$] -p $1 $2
-#}
 
 generate_ipset_rules() {
   _splice_content $SRC_DIRECT_FILES | _remove_empty | _remove_comment | _add_prefix 'add transproxy_src_direct '
@@ -263,11 +257,12 @@ parse_args() {
 
   while [ "$#" -gt 0 ]; do
     case "$1" in
-      -p|--tcp-port)
+      -t|--tcp-port)
         TCP_PORT="$2"
+        UDP_PORT="${UDP_PORT:-$TCP_PORT}"
         shift 2
         ;;
-      -P|--udp-port)
+      -u|--udp-port)
         UDP_PORT="$2"
         shift 2
         ;;
@@ -316,7 +311,7 @@ parse_args() {
         SELF_PROXY=1;
         shift 1
         ;;
-      -4|--disable-ipv6)
+      --disable-ipv6)
         DISABLE_IPV6=1
         shift 1
         ;;
