improve script by shellcheck, fix all warnings

diff --git a/transproxy6 b/transproxy6
--- a/transproxy6
+++ b/transproxy6
@@ -8,6 +8,8 @@
 # See /LICENSE for more information.
 #
 
+# shellcheck disable=SC2155,SC3043
+
 # code compatibility
 alias ip="ip -6"
 alias iptables=ip6tables
@@ -89,11 +91,11 @@ _split_by_space() {
 
 _splice_content() {
   [ -n "$1" ] || return 0
-  for file in $(_split_by_space "$1"); do cat $file; done
+  for file in $(_split_by_space "$1"); do cat "$file"; done
 }
 
 _apply_sysctl() {
-  [ $(sysctl -n "$1") != "$2" ] && sysctl -wq "$1"="$2"
+  [ "$(sysctl -n "$1")" != "$2" ] && sysctl -wq "$1"="$2"
 }
 
 _get_reserved_ip() {
@@ -115,7 +117,7 @@ _get_reserved_ip() {
 }
 
 _get_special_ip() {
-  echo $SERVER_IPS | tr ',' '\n' | grep -Ev "^([0-9]{1,3}\.){3}[0-9]{1,3}"
+  echo "$SERVER_IPS" | tr ',' '\n' | grep -Ev "^([0-9]{1,3}\.){3}[0-9]{1,3}"
   ip route get 2001:4860:4860::8888 | sed 's/^.*src \([^ ]*\).*$/\1/;q'
 }
 
@@ -125,37 +127,37 @@ _get_time() {
 
 debug() {
   [ "$VERBOSE" = 1 ] || return 0
-  local time=$(_get_time)
+  local time="$(_get_time)"
   printf "[${time}] [DEBUG]: %s\n" "$*"
 }
 
 info() {
   local green='\e[0;32m'
   local clear='\e[0m'
-  local time=$(_get_time)
+  local time="$(_get_time)"
   printf "${green}[${time}] [INFO]: ${clear}%s\n" "$*"
 }
 
 warn() {
   local yellow='\e[1;33m'
   local clear='\e[0m'
-  local time=$(_get_time)
+  local time="$(_get_time)"
   printf "${yellow}[${time}] [WARN]: ${clear}%s\n" "$*" >&2
 }
 
 error() {
   local red='\e[0;31m'
   local clear='\e[0m'
-  local time=$(_get_time)
+  local time="$(_get_time)"
   printf "${red}[${time}] [ERROR]: ${clear}%s\n" "$*" >&2
 }
 
 generate_ipset_rules() {
-  _splice_content $SRC_DIRECT_FILES | _remove_empty | _remove_comment | _trim | _add_prefix "add $TRANSPROXY_SRC_DIRECT "
-  _splice_content $SRC_PROXY_FILES | _remove_empty | _remove_comment | _trim | _add_prefix "add $TRANSPROXY_SRC_PROXY "
-  _splice_content $SRC_NORMAL_FILES | _remove_empty | _remove_comment | _trim | _add_prefix "add $TRANSPROXY_SRC_NORMAL "
-  _splice_content $DST_DIRECT_FILES | _remove_empty | _remove_comment | _trim | _add_prefix "add $TRANSPROXY_DST_DIRECT "
-  _splice_content $DST_PROXY_FILES | _remove_empty | _remove_comment | _trim | _add_prefix "add $TRANSPROXY_DST_PROXY "
+  _splice_content "$SRC_DIRECT_FILES" | _remove_empty | _remove_comment | _trim | _add_prefix "add $TRANSPROXY_SRC_DIRECT "
+  _splice_content "$SRC_PROXY_FILES" | _remove_empty | _remove_comment | _trim | _add_prefix "add $TRANSPROXY_SRC_PROXY "
+  _splice_content "$SRC_NORMAL_FILES" | _remove_empty | _remove_comment | _trim | _add_prefix "add $TRANSPROXY_SRC_NORMAL "
+  _splice_content "$DST_DIRECT_FILES" | _remove_empty | _remove_comment | _trim | _add_prefix "add $TRANSPROXY_DST_DIRECT "
+  _splice_content "$DST_PROXY_FILES" | _remove_empty | _remove_comment | _trim | _add_prefix "add $TRANSPROXY_DST_PROXY "
   _get_reserved_ip | _remove_empty | _remove_comment | _trim | _add_prefix "add $TRANSPROXY_DST_SPECIAL "
   _get_special_ip | _remove_empty | _remove_comment | _trim | _add_prefix "add $TRANSPROXY_DST_SPECIAL "
 }
@@ -199,8 +201,8 @@ apply_transproxy_rules() {
     iptables -t mangle -I PREROUTING 1 -j TRANSPROXY_SRC_PREPARE
     debug "$TRANSPROXY_NAME rules applied."
   else
-    for interface in $(_split_by_space $INTERFACES); do
-      iptables -t mangle -I PREROUTING 1 -i $interface -j TRANSPROXY_SRC_PREPARE
+    for interface in $(_split_by_space "$INTERFACES"); do
+      iptables -t mangle -I PREROUTING 1 -i "$interface" -j TRANSPROXY_SRC_PREPARE
       debug "$TRANSPROXY_NAME rules apply to $interface interface."
     done
   fi
@@ -213,17 +215,17 @@ apply_self_proxy_rules() {
   # negate matching in non-[DIRECT|PROXY] mode
   [ "$DST_DEFAULT" = "RETURN" ] || iptables -t mangle -A TRANSPROXY_DST_PREPARE -m set --match-set $TRANSPROXY_DST_DIRECT dst -j RETURN
   [ "$DST_DEFAULT" = "TRANSPROXY_DST_FORWARD" ] || {
-    iptables -t mangle -A TRANSPROXY_DST_PREPARE -p tcp -m set --match-set $TRANSPROXY_DST_PROXY dst $IPT_EXTRAS -j MARK --set-mark 1
-    iptables -t mangle -A TRANSPROXY_DST_PREPARE -p udp -m set --match-set $TRANSPROXY_DST_PROXY dst $IPT_EXTRAS -j MARK --set-mark 1
+    iptables -t mangle -A TRANSPROXY_DST_PREPARE -p tcp -m set --match-set $TRANSPROXY_DST_PROXY dst "$IPT_EXTRAS" -j MARK --set-mark 1
+    iptables -t mangle -A TRANSPROXY_DST_PREPARE -p udp -m set --match-set $TRANSPROXY_DST_PROXY dst "$IPT_EXTRAS" -j MARK --set-mark 1
   }
 
   # avoid traffic loopback issues, reference: https://github.com/v2ray/v2ray-core/issues/2621
-  [ -z "$DIRECT_MARK" ] || iptables -t mangle -A TRANSPROXY_DST_PREPARE -m mark --mark $DIRECT_MARK -j RETURN
+  [ -z "$DIRECT_MARK" ] || iptables -t mangle -A TRANSPROXY_DST_PREPARE -m mark --mark "$DIRECT_MARK" -j RETURN
 
   # only makes sense in non-DIRECT mode
   if [ "$DST_DEFAULT" != "RETURN" ]; then
-    iptables -t mangle -A TRANSPROXY_DST_PREPARE -p tcp $IPT_EXTRAS -j MARK --set-mark 1
-    iptables -t mangle -A TRANSPROXY_DST_PREPARE -p udp $IPT_EXTRAS -j MARK --set-mark 1
+    iptables -t mangle -A TRANSPROXY_DST_PREPARE -p tcp "$IPT_EXTRAS" -j MARK --set-mark 1
+    iptables -t mangle -A TRANSPROXY_DST_PREPARE -p udp "$IPT_EXTRAS" -j MARK --set-mark 1
   fi
 
   iptables -t mangle -I OUTPUT 1 -j TRANSPROXY_DST_PREPARE
@@ -240,15 +242,14 @@ apply_tcp_divert() {
 
 prepare_environment() {
   # check environment
-  modinfo xt_TPROXY &>/dev/null || { error "xt_TPROXY kernel module is not supported."; exit 1; }
-  modinfo xt_mark &>/dev/null || { error "xt_mark kernel module is not supported."; exit 1; }
+  modinfo xt_TPROXY >/dev/null 2>&1 || { error "xt_TPROXY kernel module is not supported."; exit 1; }
+  modinfo xt_mark >/dev/null 2>&1 || { error "xt_mark kernel module is not supported."; exit 1; }
   command -v ip >/dev/null || { error "ip command not found."; exit 1; }
   command -v ipset >/dev/null || { error "ipset command not found."; exit 1; }
   command -v ip6tables >/dev/null || { error "ip6tables command not found."; exit 1; }
 
   # fix environment, reference: https://nobb.site/2022/02/18/0x72/
-  _apply_sysctl net.bridge.bridge-nf-call-ip6tables 0
-  [ "$?" != 0 ] || warn "TPROXY requires net.bridge.bridge-nf-call-ip6tables=0, applied."
+  _apply_sysctl net.bridge.bridge-nf-call-ip6tables 0 && warn "TPROXY requires net.bridge.bridge-nf-call-ip6tables=0, applied."
 }
 
 flush_rules() {
@@ -261,8 +262,8 @@ flush_rules() {
   debug "routes removed."
 
   for name in $(ipset -n list | grep "$TRANSPROXY_PREFIX_IPSET"); do
-    ipset flush $name 2>/dev/null
-    ipset destroy $name 2>/dev/null
+    ipset flush "$name" 2>/dev/null
+    ipset destroy "$name" 2>/dev/null
     debug "ipset $name destroyed."
   done
   debug "ipsets destroyed."
@@ -300,7 +301,7 @@ init_iptables() {
 }
 
 parse_args() {
-  local args="$@"
+  local args="$*"
   local args_num="$#"
   while [ "$#" -gt 0 ]; do
     case "$1" in
@@ -397,9 +398,17 @@ parse_args() {
     flush_rules
     exit 0
   fi
-  ! [ -z "$TCP_PORT" -a -z "$UDP_PORT" ] || { error "[-t|--tcp-port] or [-u|--udp-port] is required."; exit 2; }
-  ! [ -z "$SERVER_IPS" -a -z "$DIRECT_MARK" ] || { error "[-s|--server] or [-m|--mark] is required."; exit 2; }
-  ! [ -n "$SERVER_IPS" -a -n "$DIRECT_MARK" ] || warn "[-s|--server] and [-m|--mark] only recommend one of them."
+  if [ -z "$TCP_PORT" ] && [ -z "$UDP_PORT" ]; then
+    error "[-t|--tcp-port] or [-u|--udp-port] is required."
+    exit 2
+  fi
+  if [ -z "$SERVER_IPS" ] && [ -z "$DIRECT_MARK" ]; then
+    error "[-s|--server] or [-m|--mark] is required."
+    exit 2
+  fi
+  if [ -n "$SERVER_IPS" ] && [ -n "$DIRECT_MARK" ]; then
+    warn "[-s|--server] and [-m|--mark] only recommend one of them."
+  fi
 }
 
 parse_args "$@"
