refine && add log functions

diff --git a/transproxy b/transproxy
--- a/transproxy
+++ b/transproxy
@@ -97,12 +97,43 @@ _get_reserved_ipv6() {
 }
 
 _get_special_ipv4() {
-  echo $SERVERS | tr ',' '\n'
+  echo $SERVERS | tr ',' '\n' | grep -Eo "\b([0-9]{1,3}\.){3}[0-9]{1,3}\b"
 }
 
-# _get_special_ipv6() {
-#   echo TODO
-# }
+_get_special_ipv6() {
+  echo $SERVERS | tr ',' '\n' | grep -Ev "\b([0-9]{1,3}\.){3}[0-9]{1,3}\b"
+}
+
+_get_time() {
+  date '+%Y-%m-%d %T'
+}
+
+debug() {
+  [ "$DEBUG" = 1 ] || return 0
+  local time=$(_get_time)
+  printf "[${time}] [DEBUG]: %s\n" "$*"
+}
+
+info() {
+  local pure='\e[0m'
+  local green='\e[0;32m'
+  local time=$(_get_time)
+  printf "${green}[${time}] [INFO]: ${pure}%s\n" "$*"
+}
+
+warn() {
+  local pure='\e[0m'
+  local yellow='\e[1;33m'
+  local time=$(_get_time)
+  printf "${yellow}[${time}] [WARN]: ${pure}%s\n" "$*" >&2
+}
+
+error() {
+  local pure='\e[0m'
+  local red='\e[0;31m'
+  local time=$(_get_time)
+  printf "${red}[${time}] [ERROR]: ${pure}%s\n" "$*" >&2
+}
 
 #log() {
 #  # 1:alert, 2:crit, 3:err, 4:warn, 5:notice, 6:info, 7:debug, 8:emerg
@@ -130,7 +161,7 @@ create_transproxy_chain() {
 
 	# PREPARE
 	-A TRANSPROXY_SRC_PREPARE -m set --match-set transproxy_dst_special dst -j RETURN
-	-A TRANSPROXY_SRC_PREPARE $IPTABLES_EXTRA_ARGS -j TRANSPROXY_SRC_AC
+	-A TRANSPROXY_SRC_PREPARE $IPT_EXTRAS -j TRANSPROXY_SRC_AC
 
 	# SRC
 	-A TRANSPROXY_SRC_AC -m set --match-set transproxy_src_direct src -j RETURN
@@ -168,15 +199,15 @@ apply_self_proxy_rules() {
 
   # negate matching in non-[DIRECT|PROXY] mode
   [ "$DST_DEFAULT" = "RETURN" ] || iptables -t mangle -A TRANSPROXY_DST_PREPARE -m set --match-set transproxy_dst_direct dst -j RETURN
-  [ "$DST_DEFAULT" = "TRANSPROXY_DST_FORWARD" ] || iptables -t mangle -A TRANSPROXY_DST_PREPARE $IPTABLES_EXTRA_ARGS -m set --match-set transproxy_dst_proxy dst -j MARK --set-mark 1
+  [ "$DST_DEFAULT" = "TRANSPROXY_DST_FORWARD" ] || iptables -t mangle -A TRANSPROXY_DST_PREPARE $IPT_EXTRAS -m set --match-set transproxy_dst_proxy dst -j MARK --set-mark 1
 
   # avoid traffic loopback issues, reference: https://github.com/v2ray/v2ray-core/issues/2621
   [ -z "$MATCH_MARK" ] || iptables -t mangle -A TRANSPROXY_DST_PREPARE -m mark --mark $MATCH_MARK -j RETURN
 
   # only makes sense in non-DIRECT mode
   if [ "$DST_DEFAULT" != "RETURN" ]; then
-    iptables -t mangle -A TRANSPROXY_DST_PREPARE $IPTABLES_EXTRA_ARGS -p tcp -j MARK --set-mark 1
-    iptables -t mangle -A TRANSPROXY_DST_PREPARE $IPTABLES_EXTRA_ARGS -p udp -j MARK --set-mark 1
+    iptables -t mangle -A TRANSPROXY_DST_PREPARE $IPT_EXTRAS -p tcp -j MARK --set-mark 1
+    iptables -t mangle -A TRANSPROXY_DST_PREPARE $IPT_EXTRAS -p udp -j MARK --set-mark 1
   fi
 
   iptables -t mangle -I OUTPUT 1 -j TRANSPROXY_DST_PREPARE
@@ -285,17 +316,21 @@ parse_args() {
         SELF_PROXY=1;
         shift 1
         ;;
-      --disable-ipv6)
+      -4|--disable-ipv6)
         DISABLE_IPV6=1
         shift 1
+        ;;
+      -e|--extra)
+        IPT_EXTRAS="$2"
+        shift 2
         ;;
       -m|--mark)
         MATCH_MARK="$2"
         shift 2
         ;;
-      -e|--extra)
-        IPTABLES_EXTRA_ARGS="$2"
-        shift 2
+      -v|--verbose)
+        DEBUG=1
+        shift 1
         ;;
       -f|--flush)
         flush_rules
